language: node_js
script:
- make archive
deploy:
  provider: releases
  api_key:
    secure: rrc5FC1RK3s5mENzeJnjrIv2uP2P/1mitfaQICyePHQUundVsvZQqepLKhprquEpikDiQ4IV+pXpN8vaCuTiQd2MVcNvJOGdVEGypFnXNzGa1A/mLu2ghHfZHpJVT5TqH+miyaOWn9p7qcQ6SJo7hC4Yx2rbpPZXaSEXjaJ5v5nV/jkm8gEibEJoGsZzisV2SZpSgjVHrRe0Hjci9mM3Is7p0Az1Z8bvVgcRC+Ffze9K6x4MFkqr68uM/+IpwSEqTNKXweztzbI9vL/13zVU4gYdxSP/Qkm8PTzlYXPlmH+M4hcw/KlBTjypAVpwZLWofNwmAiLmJjCm8cHsX7k1zJNENiE7m42/uUQs1Libu/xkBLmRgsuMMQcZzNan2D9Q8vCqMUtsPf+d42FHWTwyB27RP85abmh4F6qcdPC6lMJr1gEvqK7wqOsUrumcHi0zuszS493PJJaRfjisMMzt6xHM9kQ4RkN5++ZKdMacQrEKM2ID8tlqsDAMLh7W0HKA1yYHHfgFRFfwCocanZ+v1Q9HtYTG5VqU2m/UcMEsbkn3GKl3yC159HD7V8UtC/a9PiWfQ0M3xXC4cSsYN5R7cqj8VRoWpd1Jl+wkkyhHfbk4MfTqbHrMSzx9ZBqb6gLdcJxE7oEXwy1/tzAyRxJYM0rRlZ8xcbJN0bfw9/pMokE=
  file: build/HARImporter.zip
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: luckymarmot/Paw-HARImporter
